name: jest

on:
  workflow_dispatch:
  push:
    branches: "main"
  pull_request:
    branches: ["main"]

jobs:
  prueba-unitaria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Dependencies installing
        run: npm ci
      - name: Run unit tests
        run: npx jest
