name: jest

on:
  workflow_dispatch:
  push:
    branches: "main"
  pull_request:
    branches: ["main"]

jobs:
  prueba-unitaria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Dependencies installing
        run: npm ci
      - name: Run unit tests
        run: npx jest

  prueba-linting-codeql:
    name: analice
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        lenguages: ["javascript"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  e2e:
    needs: [prueba-linting-codeql]
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: "Secrets and variables"
        run: |
          echo "variable $USER_TEST"
        env:
          USER_VAR: ${{ vars.USER_TEST }}
          PASS_SECRET: ${{secrets.TEST_SECRET}}
