name: push test
on: 
  push:
    branches: 
      "main"
jobs:
  run-on-push-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Dependencies installing
        run: npm ci
      - name: Run tests
        run: npx cypress run --e2e --browser chrome
          
